name: pyt39
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.17=h35632f6_0
  - pip=25.2=pyhc872135_0
  - python=3.9.23=h716150d_0
  - setuptools=78.1.1=py39haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py39haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - adagio==0.2.6
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - alembic==1.16.5
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - axial-positional-embedding==0.3.12
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - black==25.9.0
      - bleach==6.2.0
      - blinker==1.9.0
      - bottle==0.13.4
      - cachetools==6.2.2
      - captum==0.8.0
      - cattrs==25.3.0
      - cdt==0.6.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.3
      - clarabel==0.11.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==4.1.0
      - colorama==0.4.6
      - colorlog==6.9.0
      - colt5-attention==0.11.1
      - comm==0.2.3
      - contourpy==1.3.0
      - coreforecast==0.0.16
      - cryptography==46.0.1
      - cvxopt==1.3.2
      - cvxpy==1.7.5
      - cycler==0.12.1
      - dacite==1.9.2
      - darts==0.37.1
      - dataproperty==1.1.0
      - datasets==3.6.0
      - debugpy==1.8.16
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - docstring-parser==0.17.0
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - evaluate==0.4.5
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.13.1
      - flatbuffers==25.2.10
      - fonttools==4.60.0
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - frstl==0.1.1
      - fs==2.4.16
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - fugue==0.9.1
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gputil==1.4.0
      - greenlet==3.2.4
      - grpcio==1.75.0
      - h11==0.16.0
      - holidays==0.81
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.0
      - hydra-core==1.3.2
      - hyper-connections==0.2.1
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipykernel==6.30.1
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jh2==5.0.10
      - jinja2==3.1.4
      - joblib==1.5.2
      - joypy==0.2.6
      - json5==0.12.1
      - jsonargparse==4.41.0
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - keopscore==2.3
      - kiwisolver==1.4.7
      - lark==1.3.0
      - lightning==2.5.5
      - lightning-utilities==0.15.2
      - linsatnet==0.1.3
      - llvmlite==0.43.0
      - lm-dataformat==0.0.20
      - lm-eval==0.4.9.1
      - local-attention==1.11.2
      - lxml==6.0.1
      - mako==1.3.10
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mbstrdecoder==1.1.4
      - mdurl==0.1.2
      - mistune==3.1.4
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.4
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - narwhals==2.6.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nfoursid==1.0.2
      - ninja==1.13.0
      - niquests==3.15.2
      - nltk==3.9.1
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numexpr==2.10.2
      - numpy==1.26.3
      - omegaconf==2.3.0
      - openmeteo-requests==1.7.3
      - openmeteo-sdk==1.21.2
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optuna==4.5.0
      - optuna-dashboard==0.19.0
      - osqp==1.0.5
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.2
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathspec==0.12.1
      - pathvalidate==3.3.1
      - patool==1.15.0
      - patsy==1.0.1
      - peft==0.17.1
      - pillow==11.0.0
      - platformdirs==4.4.0
      - plotly==6.3.0
      - portalocker==3.2.0
      - prettytable==3.16.0
      - product-key-memory==0.2.11
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - protobuf==6.32.1
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pybind11==3.0.1
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pyecharts==2.0.9
      - pygments==2.19.2
      - pykeops==2.3
      - pynvim==0.6.0
      - pyod==2.0.5
      - pyparsing==3.2.4
      - pyrootutils==1.0.4
      - pyswarms==1.3.0
      - pytablewriter==1.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - pytokens==0.1.10
      - pytorch-lightning==2.5.2
      - pytorch-test==0.1.0
      - pytz==2025.2
      - pywin32==311
      - pywinpty==3.0.0
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - qh3==1.5.5
      - referencing==0.36.2
      - reformer-pytorch==1.4.4
      - regex==2025.9.1
      - reportlab==4.4.3
      - requests==2.32.5
      - requests-cache==1.2.1
      - retry-requests==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.1.0
      - rouge-score==0.1.2
      - rpds-py==0.27.1
      - sacrebleu==2.5.1
      - safetensors==0.6.2
      - scikit-base==0.12.6
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - scs==3.2.9
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.39.0
      - shap==0.48.0
      - simplejson==3.20.2
      - six==1.17.0
      - skrebate==0.62
      - sktime==0.38.5
      - slicer==0.0.8
      - smmap==5.0.2
      - sniffio==1.3.1
      - sounddevice==0.5.3
      - soundfile==0.13.1
      - soupsieve==2.8
      - sqlalchemy==2.0.43
      - sqlitedict==2.1.0
      - stack-data==0.6.3
      - statsforecast==2.0.2
      - statsmodels==0.14.5
      - streamlit==1.50.0
      - streamlit-echarts==0.4.0
      - sympy==1.13.1
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - timm==1.0.19
      - tinycss2==1.4.0
      - tokenizers==0.22.0
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.6.0+cu126
      - torchaudio==2.6.0+cu126
      - torchinfo==1.8.0
      - torchmetrics==1.8.2
      - torchtext==0.18.0
      - torchvision==0.21.0+cu126
      - tornado==6.5.2
      - tqdm==4.67.1
      - tqdm-multiprocess==0.0.11
      - traitlets==5.14.3
      - transformers==4.56.1
      - triad==0.9.8
      - typepy==1.3.4
      - types-python-dateutil==2.9.0.20250822
      - typeshed-client==2.8.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - ujson==5.11.0
      - uri-template==1.3.0
      - url-normalize==2.2.1
      - urllib3==2.5.0
      - urllib3-future==2.14.903
      - utilsforecast==0.2.12
      - wandb==0.22.0
      - wassima==2.0.2
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - word2number==1.1
      - xarray==2024.7.0
      - xgboost==2.1.4
      - xlstm==2.0.0
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: E:\Anaconda3\envs\pyt39
